2017年 11月 06日 星期一 21:17:00 GMT
cycle: 2017110612
hydro_root: /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/
workdir: /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612

ls: /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/..//*20*: 没有那个文件或目录
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
iwait=3, sleep 30..
iwait=4, sleep 30..
iwait=5, sleep 30..
iwait=6, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
iwait=3, sleep 30..
iwait=4, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
/data02/home/fddanew/data/cycles/GWRUPPS/hydro/cycles/GFS_WCTRL/2017110612/201711071200.RTOUT_DOMAIN1 is finished, jump out of waiting --

to copy CYCLE_DATA to workdir
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/link_6hr_atmos_png_forcycle.sh /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 -6
dat: 2017110620
dat: 2017110620
dat: 2017110620
dat: 2017110620
dat: 2017110620
dat: 2017110620

bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_precp_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/precp /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.precp &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_tiles_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/tiles /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.tiles &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_evapor_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/evapor /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.evapor &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_TG.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.streamflow_TG &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_SZ.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.streamflow_SZ &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_GL.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.streamflow_GL &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_D4.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.streamflow_D4 &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_TimeSeries_SZMB.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017110612/timeseries /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017110612 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017110612/log.timeseries &
===================================
