Sun Nov 12 15:10:01 GMT 2017
cycle: 2017111206
hydro_root: /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/
workdir: /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206

iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=1, sleep 30..
iwait=2, sleep 30..
iwait=3, sleep 30..
/data02/home/fddanew/data/cycles/GWRUPPS/hydro/cycles/GFS_WCTRL/2017111206/201711130600.RTOUT_DOMAIN1 is finished, jump out of waiting --

to copy CYCLE_DATA to workdir
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/link_6hr_atmos_png_forcycle.sh /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 -6
dat: 2017111200
dat: 2017111201
dat: 2017111202
dat: 2017111203
dat: 2017111204
dat: 2017111205

bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_precp_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/precp /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.precp &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_tiles_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/tiles /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.tiles &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_evapor_SZMB_alldom.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/evapor /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.evapor &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_TG.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.streamflow_TG &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_SZ.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.streamflow_SZ &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_GL.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.streamflow_GL &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_streamflow_SZMB_D4.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/streamflow /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.streamflow_D4 &
===================================
bash /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc//script/run_plot_TimeSeries_SZMB.sh /data02/home/fddanew/data/GMODJOBS/GWRUPPS//hydro_postproc/ /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/cycledata /dev/shm/hydro_postproc/GWRUPPS/GFS_WCTRL/2017111206/timeseries /data02/home/fddanew/data/cycles/GWRUPPS/GFS_WCTRL/postprocs/web 2017111206 >& /data02/home/fddanew/data/cycles/GWRUPPS/zout/hydro_postproc/cyc2017111206/log.timeseries &
===================================

start monitor plot tasks
--wait: 0 (60 second)
--wait: 1 (60 second)
--wait: 2 (60 second)
--wait: 3 (60 second)
--wait: 4 (60 second)
--wait: 5 (60 second)
--wait: 6 (60 second)
--wait: 7 (60 second)
--wait: 8 (60 second)
--wait: 9 (60 second)
--wait: 10 (60 second)
--wait: 11 (60 second)
--wait: 12 (60 second)
--wait: 13 (60 second)
--wait: 14 (60 second)
--wait: 15 (60 second)
--wait: 16 (60 second)
--wait: 17 (60 second)
--wait: 18 (60 second)
--wait: 19 (60 second)
--wait: 20 (60 second)
All finished
